apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: csharp-web
  template:
    metadata:
      labels:
        app: csharp-web
    spec:
      containers:
      - name: web
        image: csharp-web:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081