[phases.setup]
nixPkgs = ["dotnet-sdk_10"]

[env]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:8080"
PORT = "8080"

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "dotnet out/CSharpWithDocker.dll"