[phases.setup]
nixPkgs = ["dotnet-sdk_10"]
nixpkgsArchive = 'ab8dcb27e7a326d171c6c484de658e3a9d518b43'

[env]
ASPNETCORE_ENVIRONMENT = "Production"
ASPNETCORE_URLS = "http://0.0.0.0:8060"
PORT = "8080"

[phases.build]
cmds = [
  "dotnet restore",
  "dotnet publish -c Release -o out"
]

[start]
cmd = "dotnet out/CSharpWithDocker.dll"